# Generated by Django 6.0.5 on 2026-05-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0002_appointmentbookings_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbookings',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='appointmentbookings',
            name='phone',
        ),
    ]
