# Generated by Django 6.0.5 on 2026-05-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0003_rename_name_appointmentbookings_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmentbookings',
            new_name='register',
        ),
    ]
