# Generated by Django 6.0.5 on 2026-05-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0004_rename_appointmentbookings_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='appointmentbooking',
        ),
    ]
